### ISSUE TITLE
simpleError: `col_names` must be TRUE, FALSE or a character vector

### ISSUE THREAD

**Issue by geotheory** [Robsteranium/csvwr#1]
Following the [basic usage instructions](https://github.com/robsteranium/csvwr) gets me:

```
require(csvwr)
#> Loading required package: csvwr

d <- iris[sample(150,10),]
s <- derive_table_schema(d)
m <- create_metadata(tables=s)
j <- jsonlite::toJSON(m)
cat(j, file="metadata.json")
write.csv(d, 'data.csv')

read_csvw_dataframe("data.csv", "metadata.json")
#> $error
#> <simpleError: `col_names` must be TRUE, FALSE or a character vector>
#> 
#> $filename
#> [1] "data.csv"
#> 
#> $dialect
#> list()
#> 
#> $group_schema
#> list()

```

**Comment by Robsteranium** [comment]
Thanks for the report @geotheory.

It looks like the readme and vignette are wrong. It works if you instead call `create_metadata` like:

    m <- create_metadata(tables=list(list(tableSchema=s)))

i.e. the `tables` are a list of tables, each table itself being a list having a `tableSchema`.

I'll update the documentation and add a test case for round-tripping like this. I think the metadata can look a little different in the single-table case (the table group being optional) so I'd like to double-check with the standard first.

**Comment by geotheory** [comment]
That works :) Any plans to support factor class?

**Comment by Robsteranium** [comment]
I've fixed the docs and added a test case, thanks.

Indeed the metadata is different in the single table case, I've created #2 to explore this. 

Factors are a good idea. I've created #3 for that.
