### ISSUE TITLE
Use-case working with temp files

### ISSUE THREAD

**Issue by ghost** [Robsteranium/csvwr#10]
What's the recommended way to work with files from the internet?

I'm providing my users with a notebook so they can explore a remote dataset. If I download my json and csv to temp files, the uri of the table breaks, so I'm having to download them to named local files which, ok might be the best for large files anyway, but if I'm wanting a toe in the water with a dataset, it would be cool to be able to just slurp a few lines of csv into a string and fire those into a dataframe...

Same issue if the uri of the table in the json file is absolute.

How do you imagine best practice for this sort of workflow? Thanks!

**Comment by Robsteranium** [comment]
Hi @gjhltn :wave:

I would recommend using the URL of the metadata e.g.

```
read_csvw("https://raw.githubusercontent.com/Robsteranium/csvwr/master/inst/extdata/computer-scientists.json")
```

The metadata must include a table-url and {csvwr} will use that to retrieve and parse the table. If the URL isn't absolute (as here `"url": "computer-scientists.csv"`) it will be expanded relative to the metadata's location. It'll also use the metadata to parse the CSV appropriately - you don't need to do this yourself.

If you don't want to download the data from the internet and use a local copy instead, you can override the metadata at read time. This let's you keep the URL in the metadata for others who won't have a local copy. I've packaged the above CSV file as part of {csvwr} for testing and we can use the  `csvwr::csvwr_example` function to yield the path on your disk where this was installed. We can use this to retreive the local CSV and parse it using the remote metadata:
```
read_csvw(
  csvwr_example("computer-scientists.csv"), # e.g. ~/R/x86_64-pc-linux-gnu-library/4.3/csvwr/extdata/computer-scientists.csv
  metadata="https://raw.githubusercontent.com/Robsteranium/csvwr/master/inst/extdata/computer-scientists.json"
)
```

The metadata location can be a local path too (i.e. `read_csvw("data.csv", "metadata.json")`).

Tbh the spec is a bit "simple made easy" on this topic! You can load either the CSV or the JSON and each are supposed to [find the other](https://w3c.github.io/csvw/syntax/#locating-metadata) but at least once you've got your head around it, it's a flexible and convenient interface.

**Comment by ghost** [comment]
Thanks. The key thing here I had overlooked was that I could pass a URI to read _csv. That will solve it!

Yeah no arguments from me that csvw makes the easy hard in several respects but to be fair I think the problem here is actually inherited from linked data. TBL's ill-advised pun on URIs where they are used as both guids and network locations was not really a very good idea imo.

(It's also wildly unclear to me how base paths are supposed to work in csvw and the spec is to my eyes not good at clarifying this.)

anyways many thanks for the answer and for the v cool library, which works a treat even for a total noob such as myself! Thanks man.
